version: '3.1'

services:

  polr:
    build: .
    restart: always
    ports:
      - 8080:80
    environment:
      DB_HOST: database
      DB_DATABASE: polr
      DB_USERNAME: root
      DB_PASSWORD: root
      POLR_SETUP_RAN: 'true'
      SETTING_PUBLIC_INTERFACE: 'true'
      SETTING_SHORTEN_PERMISSION: 'false'
      POLR_BASE: 32
      APP_ADDRESS: 51.68.85.78:8080
    networks:
      - back

  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - /tmp/mysql/:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: polr
    networks:
      - back

networks:
  back: